---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(janitor)
```
```{r}
avocado <- read_csv("data/avocado.csv") %>% clean_names()
avocado_dict <- read_csv("data/data_dict.txt")
glimpse(avocado)
```
```{r}
avocado_tidy <- avocado %>% 
  #remove x1 column as not sure what it means
  select(-x1) %>% 
  mutate(date = str_extract(date, "\\-[\\d]{2}")) %>% 
  mutate(date = case_when(date == "-12"| date == "-01"| date == "-02" ~ "winter",
                          date == "-03"| date == "-04"| date == "-05" ~ "spring",
                          date == "-06"| date == "-07"| date == "-08" ~ "summer",
                          date == "-09"| date == "-10"| date =="-11" ~ "autumn")) %>% 
  mutate(type = as_factor(type)) %>% 
  mutate(year = as_factor(year)) %>% 
  select(-region)
  
avocado_tidy
```
```{r}
alias(average_price ~ ., data = avocado_tidy)
#no any other correlations found in data
```
```{r}
summary(avocado_tidy)
#there is non NA in data
#as it is all quantity there is no need to standardise the data
```
```{r}
library(leaps)
```

```{r}
regsubsets_forward <- regsubsets(average_price ~ ., data = avocado_tidy, nvmax = 11, method = "forward")
sum <- summary(regsubsets_forward)
```

```{r}
sum$which
```
```{r}
plot(regsubsets_forward, scale = "adjr2")
plot(regsubsets_forward, scale = "bic")
#Plots showing the same results for variables that most date, various PLU, xl bags and 
#year contribute to R2 equally.
```
```{r}
plot(sum$rsq, type = "b")
plot(sum$bic, type = "b")
#Plots show that 8 variables required to get the best BIC and R2 value.
```
```{r}
regsubsets_forward <- regsubsets(average_price ~ ., data = avocado_tidy, nvmax = 8, method = "forward")
summary(regsubsets_forward)
```
```{r}
n_data <- nrow(avocado_tidy)
test_index <- sample(1:n_data, size = n_data*0.2)

test  <- slice(avocado_tidy, test_index)
train <- slice(avocado_tidy, -test_index)
```

```{r}
model <- lm(average_price ~ type + year + date, data = train)
summary(model)
#all variables are significant 
```
```{r}
par(mfrow = c(2, 2))
plot(model)
#residuals distirbution is good
```
```{r}
model <- lm(average_price ~ ., data = train)
summary(model)
#all bags variables are not significant for predictions
```
```{r}
model <- lm(average_price ~ type + date  +x4046 +x4225 + x4770 +
              year, data = train)
summary(model)
```
```{r}
par(mfrow = c(2, 2))
plot(model)
#residuals are independent and well distributed
```
```{r}
model_int <- lm(average_price ~ type + date  +x4046 +x4225 + x4770 +
              year + type:date + type:x4046 + type:x4225 +type:x4770, data = train)
summary(model_int)
anova(model, model_int)
#Interactions show significant difference between the model without them
```
```{r}
predictions <- predict(model_int, newdata = test)
mean((predictions - test$average_price)**2)
```
```{r}
predictions <- predict(model_int, newdata = train)
mean((predictions - train$average_price)**2)
```
```{r}
library(relaimpo)
calc.relimp(model_int, type = "lmg", rela = TRUE)
```
```{r}
broom::glance(model_int)
```
```{r}
broom::glance(model)
```
model_int is the best model after all the checks for predictions of average_price for avocados. However, it can predict only around 48%.
```{r}
summary(model_int)
```
```{r}
library(glmulti)
```

```{r}
glmulti_fit <- glmulti(
  average_price ~ ., 
  data = train,
  level = 1, # 2 = include pairwise interactions, 1 = main effects only (main effect = no pairwise interactions)
  minsize = 1, # no min size of model
  maxsize = -1, # -1 = no max size of model
  marginality = TRUE, # marginality here means the same as 'strongly hierarchical' interactions, i.e. include pairwise interactions only if both predictors present in the model as main effects.
  method = "h", # try exhaustive search, or could use "g" for genetic algorithm instead
  crit = bic, # criteria for model selection is BIC value (lower is better)
  plotty = FALSE, # don't plot models as function runs
  report = TRUE, # do produce reports as function runs
  confsetsize = 10, # return best 10 solutions
  fitfunction = lm # fit using the `lm` function
)
```

```{r}
summary(glmulti_fit)
```

```{r}
# lowest BIC model with main effects
lowest_bic_model <- lm(average_price ~ type + year + quarter + total_volume + x_large_bags + region, data = train)
results <- results %>%
  add_row(
    tibble_row(
      name = "lowest bic", 
      bic = bic(lowest_bic_model),
      rmse_train = rmse(lowest_bic_model, train),
      rmse_test = rmse(lowest_bic_model, test)
    )
  )

# try adding in all possible pairs with these main effects
lowest_bic_model_all_pairs <- lm(average_price ~ (type + year + quarter + total_volume + x_large_bags + region)^2, data = train)
results <- results %>%
  add_row(
    tibble_row(
      name = "lowest bic all pairs", 
      bic = bic(lowest_bic_model_all_pairs),
      rmse_train = rmse(lowest_bic_model_all_pairs, train),
      rmse_test = rmse(lowest_bic_model_all_pairs, test)
    )
  )
```

```{r}
# try a model with all main effects
model_all_mains <- lm(average_price ~ ., data = train)
results <- results %>%
  add_row(
    tibble_row(
      name = "all mains", 
      bic = bic(model_all_mains),
      rmse_train = rmse(model_all_mains, train),
      rmse_test = rmse(model_all_mains, test)
    )
  )

# try a model with all main effects and all pairs
model_all_pairs <- lm(average_price ~ .^2, data = train)
results <- results %>%
  add_row(
    tibble_row(
      name = "all pairs", 
      bic = bic(model_all_pairs),
      rmse_train = rmse(model_all_pairs, train),
      rmse_test = rmse(model_all_pairs, test)
    )
  )
```

```{r}
# try a model with all main effects, all pairs and one triple 
model_all_pairs_one_triple <- lm(average_price ~ .^2 + region:type:year, data = train)
results <- results %>%
  add_row(
    tibble_row(
      name = "all pairs one triple",
      bic = bic(model_all_pairs_one_triple),
      rmse_train = rmse(model_all_pairs_one_triple, train),
      rmse_test = rmse(model_all_pairs_one_triple, test)
    )
  )
```

```{r}
results <- results %>%
  pivot_longer(cols = bic:rmse_test, names_to = "measure", values_to = "value") %>%
  mutate(
    name = fct_relevel(
      as_factor(name),
      "lowest bic", "all mains", "lowest bic all pairs", "all pairs", "all pairs one triple", "all pairs multi triples"
    )
  )
```

```{r}
results %>%
  filter(measure == "bic") %>%
  ggplot(aes(x = name, y = value)) +
  geom_col(fill = "steelblue", alpha = 0.7) +
  labs(
    x = "model",
    y = "bic"
  ) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  geom_hline(aes(yintercept = 0))
```

```{r}
results %>%
  filter(measure != "bic") %>%
  ggplot(aes(x = name, y = value, fill = measure)) +
  geom_col(position = "dodge", alpha = 0.7) +
  labs(
    x = "model",
    y = "rmse"
  ) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

