---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
diamonds <- read_csv("diamonds.csv")
glimpse(diamonds)
```
```{r}
library(GGally)
ggpairs(diamonds[,c("carat", "x", "y", "z")])
```
```{r}
diamonds <- diamonds %>% 
  select(-x, -y, -z)

diamonds
```
```{r}
ggpairs(diamonds)
```
```{r}
diamonds %>% 
  ggplot(aes(x = carat, y = price)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE)
```
```{r}
diamonds %>%
  ggplot(aes(x = cut, y = price)) +
  geom_boxplot()
```
```{r}
unique(diamonds$cut)
```

```{r}
library(fastDummies)
```
```{r}
diamonds_dummy <- diamonds %>% 
  dummy_cols(select_columns = "cut", remove_first_dummy = TRUE,
             remove_selected_columns = TRUE) %>% 
  dummy_cols(select_columns = "clarity", remove_first_dummy = TRUE,
             remove_selected_columns = TRUE) %>% 
  dummy_cols(select_columns = "color", remove_first_dummy = TRUE,
             remove_selected_columns = TRUE) 

diamonds_dummy
```
```{r}
diamonds_dummies <- dummy_cols(diamonds, select_columns = c("cut", "clarity", "color"), remove_first_dummy = TRUE)
glimpse(diamonds_dummies)
```

```{r}
model <- lm(price~carat, data = diamonds)
summary(model)
```
```{r}
library(ggfortify)
autoplot(model)
```
```{r}
mod2_logx <- lm(price ~ log(carat), data = diamonds)
par(mfrow = c(2,2))
plot(mod2_logx)
```

```{r}
model <- lm(log(price) ~ log(carat), data = diamonds)
summary(model)
autoplot(model)
```
```{r}
model <- lm(log(price) ~ log(carat) + color, data = diamonds)
summary(model)
autoplot(model)
```

```{r}
mod3_clarity <- lm(log(price) ~ log(carat) + clarity, data = diamonds)
summary(mod3_clarity)
```
```{r}
ratio <- exp(1.114625)
ratio
```
Taken from clarity IF estimate from summary of model.
so, on average, the price of an IF diamond will be approx. 3 times higher than that of I1 diamond of same carat.
```{r}
mod4_clarity_inter <- lm(log(price) ~ log(carat) + clarity + log(carat):clarity, data = diamonds)
summary(mod4_clarity_inter)
```
```{r}
anova(mod3_clarity, mod4_clarity_inter)
```
```{r}
diamonds %>%
  ggplot(aes(x = log(carat), y = log(price), colour = clarity)) +
  geom_point(alpha = 0.1) +
  geom_smooth(method = "lm", se = FALSE) +
  facet_wrap(~ clarity)
```
not much evidence that the gradient of the line varies significantly with clarity


