---
title: "meteorites_data_analysis"
author: "VM"
date: "31/10/2020"
output: html_document
---
```{r}
library(tidyverse)
library(janitor)
```
Read clean data.
```{r}
clean_data_meteorites <- read_csv("../data/clean_meteorites.csv")
```
```{r}
clean_data_meteorites
class(clean_data_meteorites)

clean_data_meteorites <- as.data.frame(clean_data_meteorites) %>% clean_names()

clean_data_meteorites
```
10 largest meteorites.
```{r}
clean_data_meteorites %>%
  select(name, mass_g, year) %>% 
  arrange(desc(mass_g))  %>% 
  slice_max(order_by = mass_g, n=10)
```
Average mass of different meteorites.
```{r}
clean_data_meteorites %>% 
  filter(fall == "fell") %>% 
  summarise(avg_mass_fell = mean(mass_g))
```
```{r}
clean_data_meteorites %>% 
  filter(fall == "found") %>% 
  summarise(avg_mass_found = mean(mass_g))
```
Meteorites per year since 2000.
```{r}
clean_data_meteorites %>% 
  filter(year >= 2000) %>% 
  group_by(year) %>% 
  summarise(total_per_year = n_distinct(name)) %>% 
  arrange(year)
```
```{r}
clean_data_meteorites %>% 
  summarise_all(funs(sum(is.na(.))))
```
Biggest meteorite found per year.
```{r}
clean_data_meteorites %>% 
  drop_na() %>% 
  filter(fall == "found") %>%
  group_by(year) %>% 
  summarise(big_per_year = max(mass_g)) %>% 
  arrange(year)

```
Biggest meteorite fell per year.
```{r}
clean_data_meteorites %>% 
  drop_na() %>% 
  filter(fall == "fell") %>%
  group_by(year) %>% 
  summarise(big_per_year = max(mass_g)) %>% 
  arrange(year)

```
The 10 biggest meteorites.
```{r}
clean_data_meteorites %>% 
  drop_na() %>% 
  slice_max(mass_g, n=10) %>% 
  arrange()
```
The 10 smallest meteorites.
```{r}
clean_data_meteorites %>% 
  drop_na() %>% 
  slice_min(mass_g, n=10) %>% 
  arrange()
```
Median latitude and longitutde.
```{r}
clean_data_meteorites %>% 
  select(latitude, longitude) %>% 
  summarise(lat_md = median(latitude), long_md = median(longitude)) 

```
Change g to kg.
```{r}
clean_data_meteorites %>% 
  mutate(mass_kg = mass_g/1000)
```

